name: GitHub Actions Demo
on: [push]
jobs:
	Explore-GitHub-Actions:
		runs-on: ubuntu-20.04
		steps:
			- run: echo "Job was triggered by ${{ github.event_name }}"
			- run: echo "Job is running on ${{ runner.os }}"
			- run: echo "The branch is ${{ github.ref }}"
			- name: Check out code
			  uses: actions/checkout@v2
			- run: echo "{{ github.repository }} cloned to runner"
			- name: List files in repo
			  run: |
				ls ${{ github.workspace }}
			- run: echo "Status: ${{ job.status }}"
